version: '3.7'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - './front:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
     - "3000:3000"